name: budgen
description: Flutter project.
publish_to: 'none' 
version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  mobx: ^1.2.1
  flutter_mobx:  ^1.1.0+2
  json_annotation: ^3.1.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  http: ^0.12.1
  http_parser: ^3.1.4
  googleapis: ^1.0.0
  googleapis_auth: ^0.2.12+1
  flutter_svg: ^0.19.1
  uuid: ^2.2.2
  package_info_plus: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  mobx_codegen: ^1.1.2
  sqflite: ^1.3.2+4

flutter:

  uses-material-design: true
